# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      MainEnvironment:
        type: choice
        description: 'Main environment'
        required: true
        options:
          - dev
          - test
          - prod

jobs:  
  deploy:
    if: inputs.MainEnvironment == 'dev'
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
      
    - name: Load variables
      shell: bash
      run: |
        cat dev-enva.sh >> $GITHUB_ENV

    - name: Show variables
      shell: bash
      run: |
        env

        
        
        
